language: python
python:
- '2.7'
sudo: required
services:
- docker
install:
- pip install dxpy
env:
  global:
    #TRAVIS_TOKEN
    #QUAY_LOGIN
    #QUAY_PASSWORD
  - secure: PP/M68iH20+Z+0spkbY8VgW0iPBT510+BBdiXoPvCF9dqnGNH+14Qm/PjvYR2pAyOvzhqP4h9L9Lcwdzahv3asVT8UkkEtex5BK6hx5EtYKfuZ90Lzl6cMyFIDN3sXLBfYOoW6KT3yBnuCFq6gW6cg8xUy0dAccECkXbLJFsqflQcjgKQEGJaH2vLAxQ2Byj4k/6tsLX0SyYsvRmotMD7VMpVschig+VhH2+v3B11cN9cyJFl8d/R2iKQrWkwwQPiPqhlyar41nOptjLl0k/i7utA30j8KUFD/VbDsvBnRjCachjd/zb44j7zhtW4pJYq+vdizJWPz5jNGqHD/0TZBUc6Yxf4WgmAHcleA22KUeLCsqI93/RZJKOLHwMVx7mCzKg6wHKx0FVJ5G/IXNrhngXH8y5VTkHG5hZECQzrmuMekw0mSuXV7uC35NvxMd+Z0kvwzbZsm04TeSZoXE2nuYSioKhiefUvrmeIWpXTvHZVmI9NnVsGdNN7rKTD/N54Ogawf5D5Fz2v4nQMKeCRie3H7LYnGyZqT6EfFO2GsWqoZJPwoTy5u8MTzl4zjQt12gLBHTvN9vZZb+k9pDdC608hqioFWqApVY7vCihMugMBgVKfydNu74roZsh4u06xNoQMDzHaBXyVHj+i5U1wAZCmJKHm99KiQ3wCiy9f0s=
  - secure: IDBZ/1Mi0xz6Udj9RT44z/JejQVU0hOQN4sYHbFvkpPdBo7UmH9U7Rs3neZ9GbnxWfIvmuvYUdptBakhyANCJmHbTSbhoEMHZU59pLwjbee0v/OYB+RFDMm9buGuVNzBC9HXVW0qUm+kN8QnZ7OCcA+l/m4K99GJqbs+8fhloW5qErkuOmI9XDMJHZz4KUfw/0glnMvAZWIW6gn3PmBsUIrtQcT4rbD6+UI3sIkPUeNPn7O2/g0yDf4+e22rl2NjmkxcFg+jURtsaYikUNmR5f8F4C5l3Y7VGHgeLlQYZbMbIFDTcI8QdXU4SR2dqBWPYdM9j1bAkCzmHsO/unKY/wZ4xW7sFHGEIfUJgI0O7nzmKQPe7mscfucw0ljR2g2JfpkIVG1i03SrVRL2Tidd2HjnETsEfFL2bMJ8qDFA/VAw9eMve8tTGAPEOT+Nzr+olgM+iJq/VLb1jdlWhkcBRWfMAYH+Q8e+/QTa5YKztUQPI6tnLx9T1OHpkawd7bZTKHEocASdNnGiUxr3WwG7vN82dpQ1Pgxh+i0cnSm+kIqr5l9SeLLin6ZmQRfjZKp6xLu8Z0yuF+X2q0drlO7ZcixQxDYKwh54g/nS0fwpn5KF9KiX7oTY7bcweY9l5qVBfJW53TufyeWRZ6NW1dguVITWQUQ0cYwptiXgxIBNQJA=
  - secure: kG8afnga6Z9Npy7qOfj2lfTJVu5wwA72s1UkQ4K4YW7HNGmCxb3FlosYbvDqgTvgSyla8pvK9T0RXvJWtiRi8TuRX05qmIwURfj77+pXPk1qxt5IM0Xeg5R6DeGK2reBHKcKO+vkLDpMpPn5jw02jSK6CFsCmU5GtUSWmctnCKwlClUIh2BCOP4gORW0Q/h2V8B9shltAYJH5fNXDCPk6SP/qmhjjGMkIYoRXRQS8Y8GN8vKkZz8vqYnZVQmx2kny+lf0/nOBly8ACvQOcWiyrafNyHPsK14NuRQb0uWVPB3+uiYfVqjUt/qEazcSAwAf8N9XqLd/U8R7UmpHfR20/XuQN4nNkZF3czH19cgZwp7hrEy2v7o4+fLTE6onJmN5gdsumG3yGxIqLSpTANI1AOhqa1uZOKKWDy1dNQQXXIxSr8juf5pkPMhRib+SeSvR86dPcGBHbB8GKafqLNX4MDNh/X4KKVG8uiw+4DgsSqKFhSllm8m15fgXxe3Dg5t6rIFYFU1aF6LxQLtr4IcrwC1BJTJL3s8m/17smHRQU0SNsgwKglXYAqImr5IJ/J2d6hxPRS11FjuFb8IW/EYM0vMZ/9GPVCMuR1qw6DHcVkREFTzmDYsURtjebMRnhGnR52SI92ovxpbTd+y7uW7sm+36sYHDMvrjV15ui1yTnU=
script:
- docker build -t hellodocker HelloDocker/
- python testuselessfunctions.py
- ./test.sh
after_success:
- docker login quay.io -u="$QUAY_LOGIN" -p="$QUAY_PASSWORD"
- docker commit `docker ps -l | awk '{print $1}' | tail -n 1` quay.io/ottojolanki/pipeline-images
- docker push quay.io/ottojolanki/pipeline-images
- ./trigger-cwl-build.sh


