language: python
python:
- '2.7'
sudo: required
services:
- docker
install:
- pip install dxpy
env:
  global:
    #QUAY_LOGIN
    #QUAY_PASSWORD
    #TRAVIS_TOKEN
  - secure: JOLnW5AVgWkQEEtC2qzljZ2h9VQhhCZt5ijyEn8ZPxaMUbYiJBNzmvLMgu1ifQzVLde+VbCz/auoGPnyEvZpaOzaWsxHENzufRlataSlwMdrDG7ix2kkPs/ubV+O41jgnOYS6iQQhy30W+8ePUzYXEDzU4TKXL+mBuynMOJGvXIVrOsRE6bNv9nQzpSKEy1fN2tUS+f+/8ENRSjMgHNdjcx2h/eYGxEcoijMCzlXGNpgQ3IYv04M8jbETW8cDIoOnsBgHc0D8RNXj3ZxeMHvT74Xy8OdVpvXOlwAVE2pMLTuoeZ6WJgYdWRsvGbtVDmZ8U+Xkj/skccsPIZQQP22HfQg0x5Jutr63vL+K8QyYSmmyrwo7/8u8NWnz02Tl1K0X3lSX/IYYjtQSQb+788Y7As0txVq2L+TdRH126Y8k1AU5xgO66X7jDekg0EgHbEpLbdfDLU8hQf7Z2RBLsgqZVBqz87K2KoKkVdXHS8+i3YDK/7JBkgUzEJ5oTNsitXTxzGfdg826Y33Dngnk/Dm0e1X3FOrNjYBCE7TCMNO4XLCv8bhWexefFbtmFKbZQYhmoxsq19ERm9ZDM1Nh4vtFpabh1x+0hDY+iNVULvR7U48WhAQLnoRwOtIDpjTXLFWqL8RtUXoLgZnFCkbkpyKcvbLMTEYVEADpcaWMB0W0rM=
  - secure: N/nWRxkWTEEYE6rLpuq8RCmaOfk3XW6sG0uW3VNJM0rfBjj72mupf6cykjEPczWGYMsmyaZFoHkvxD2C7BQdMTHQFQX+vGrg/uZ0YxwsLunhUCzlusvDX9oqacQlVoO9v2brlhT5Zc0FublvI82ogCcOyfuo9fQsW2Q8LK+0FK1gC7odKTISNQO3J+L1zERbZ6/16SK1qtNG9F1HLan7Y+B+4pdGgguFbAJ+0wNfInlVh0b/ofOT5pvQXac7Ly6SL5+q5nwfK2Uj2typasNUZGBQ500GOIQX4GcYTetb+GQrwtLlU0y8FxnSSOy4CdhfqQ/GF7bwEZjH6lxd5A0KF9iLc5IRpw7dZgrsSqrgRu9sERQF+QRAm64gcZyxNEF7VSNFKVRQb/GHGdxoLWqdlXjatrl3aB/B0WlFNVG667pSKiINbmTVB87/BDVYR5ET8rgNCI6WrgLFbNhlpZg8/lQri6L2T+tOtLXspGixsTmiBDsuJsaO9B4KxVeEvykYg98NvSPPtvG0V08DYy7PgywAyi8jultFxXiCxeJ1qLD0YFYoW7Ruvd7UMAnX6yLmDvzi0STTy4HGSsnXCum+Z3UwFhHbKogWFSImBr2iM9vwCw3px5k+hmmx4wzMBKnlj9TE33bJtkiY+md4+ZVm1yP9ybdgxZ5Dk/sFfrCzSBA=
  - secure: rTpPnQKFiuxHwzyE47tKOYgp2oCHU5d/QkHF42QO8BHIseBWfgKOpy7C/xcCO779jCDx+rXoGof+0ujwnPa9h7GUElG+nyxm5Zc+/eAb7AQEsykUPk0lJDTulzkTlcak1hLFEh9SquMK5nijf0nD95wABbvZkLVGSY2CpDU3HAs50eSGawSonfo5YqKJEYBcnqkwlbZfiDcrdbHFz/q/UcG7KIrYxjir0DYxfVQcs+lyy44WjrjJE9cHJdVXpdc4LRSFbZLvCF5EEnYm5iUCCGW9bH9MlP0NaRn/NLZiV2OtLA2Sh0s8lYx5TsIS+zJkzpK8JvE2A4V5zFV7XPY2RrqD93YXqGVRO8q4Wht1waNLoC8q1xy8TuHCaiCyE8eRBrsXL0g2T1qMvKEhQSISXA2wNzt00Awbh4gZhN6Ut2ZcZ4c3Ymonf/4Pq1gdKrXXbTc+BPc62ohVxlaENT4ku+1htqd9/q3RUkKIpnoTLz9QnDNUaprAv4jW/whq9wOVJIYH7nkS3YjmJ5MB0FHNuwVi7Tp+5dNbb8gR+1YkKavPMFg26bIFpdRUC9Wf9tzorXIr5vp46iQAE6VXdgANmjW+qcIMcW2pXD1/s1oOBYWkW9tudYbhDTne2mtwp7Abk5YWxw1ipTU94v7dnz8l2Tssko3KbsSDRklIZVbGf9A=
script:
- docker build -t hellodocker HelloDocker/
- python testuselessfunctions.py
- ./test.sh
after_success:
- docker login quay.io -u="$QUAY_LOGIN" -p="$QUAY_PASSWORD"
- docker commit `docker ps -l | awk '{print $1}' | tail -n 1` quay.io/ottojolanki/pipeline-images
- docker push quay.io/ottojolanki/pipeline-images
- ./trigger-cwl-build.sh
